version: '2.1'
services:
  nginx:
    build:
        context: ./nginx/
    container_name: 'nginx'
    ports:
      - '80:80'
      - '433:433'
    depends_on:
      - php
    volumes:
      - ./content/:/usr/share/nginx/html:rw
    environment:
      FPM_HOST: 'php'
      FPM_PORT: '9000'
  php:
    build:
        context: ./php/
    container_name: 'php'
    depends_on:
      - postgres
    environment:
      RUN_COMPOSER: "yes"
      GITHUB_TOKEN: $MY_TOKEN
      COMPOSER_PACKAGE: 'laravel/laravel'
    volumes:
      - ./content/:/usr/share/nginx/html:rw
      - ./laravel.env:/usr/share/nginx/laravel.env
      - composer-cache:/root/.composer/cache 
  postgres:
    image: postgres:11
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'laravel'
      POSTGRES_PASSWORD: 'laravel'
      POSTGRES_DB: 'laravel'
      TZ: 'GMT+9'
      PGTZ: 'GMT+9'
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  adminer:
    build:
        context: ./adminer/
    container_name: 'adminer'
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SYSTEM: "pgsql"
      ADMINER_DEFAULT_SERVER: "postgres"
      ADMINER_DEFAULT_USERNAME: "laravel"
      ADMINER_DEFAULT_PASSWORD: "pass"
      ADMINER_DEFAULT_DATABASE: "laravel"
volumes:
  composer-cache:
  postgres-data:
