#!/bin/sh
if [ -z "$GITHUB_TOKEN" ]; then
composer global require hirak/prestissimo
fi

if [ $RUN_COMPOSER = "yes" ]; then
echo "{\"github-oauth\": {\"github.com\": \"${GITHUB_TOKEN}\"}}" > /usr/share/nginx/auth.json
if [ -e /usr/share/nginx/html/composer.lock ]; then
    #if composer.lock exists, just update the project.
    (cd /usr/share/nginx/html && composer update)
elif [ -e /usr/share/nginx/html/composer.json ]; then
    #if composer.json exists, install the project.
    (cd /usr/share/nginx/html && composer install)
else
    #if neither exists, create the project.
    mkdir /usr/share/nginx/html
    (cd /usr/share/nginx/ && composer create-project --prefer-dist $COMPOSER_PACKAGE html)
    chmod -R 777 /usr/share/nginx/html/storage
    chmod -R 777 /usr/share/nginx/html/bootstrap
    (cd /usr/share/nginx/html && php artisan key:generate)
    echo "{\"github-oauth\": {\"github.com\": \"${GITHUB_TOKEN}\"}}" > /usr/share/nginx/html/auth.json
fi

if [ -e /usr/share/nginx/laravel.env ]; then
rm -rf /usr/share/nginx/html/.env
cp /usr/share/nginx/laravel.env /usr/share/nginx/html/.env
fi

fi

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

cd chmod 777 /usr/share/nginx/html/storage/logs/ -R && \
php artisan migrate:fresh --seed
chmod 777 /usr/share/nginx/html/storage/logs/ -R

exec "$@"
